# frozen_string_literal: true

cask "flightdeck" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version "1.0.1"
  sha256 "c4d101ee50ac427e14e6857db8a9d274c7f44a41e4ba99aa7fd817666e67e502"

  url "https://github.com/saadjs/FlightDeck/releases/download/v#{version}/FlightDeck-v#{version}.zip"
  name "FlightDeck"
  desc "Tiling window manager inspired by i3"
  homepage "https://github.com/saadjs/FlightDeck"

  conflicts_with cask: "flightdeck-dev"
  depends_on macos: :ventura

  app "FlightDeck-v#{version}/FlightDeck.app"
  binary "FlightDeck-v#{version}/bin/flightdeck"
  binary "FlightDeck-v#{version}/shell-completion/zsh/_flightdeck",
         target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_flightdeck"
  binary "FlightDeck-v#{version}/shell-completion/bash/flightdeck",
         target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/flightdeck"
  binary "FlightDeck-v#{version}/shell-completion/fish/flightdeck.fish",
         target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/flightdeck.fish"

  Dir["#{staged_path}/FlightDeck-v#{version}/manpage/*"].each { |man| manpage man }
end
