# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genie < Formula
  desc "Translate plain English into shell commands"
  homepage "https://github.com/saadjs/genie-cli"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.4/genie_darwin_amd64.tar.gz"
      sha256 "d25de35511bcb328a4a98c54c52d0a03c00f1caf0e1d4e76c7459a76c073df4d"

      define_method(:install) do
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.4/genie_darwin_arm64.tar.gz"
      sha256 "50e611afb008cdfbcfeb2e9e1b1565293fd65e847216b93b13ce9b23eb6332b5"

      define_method(:install) do
        bin.install "genie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.4/genie_linux_amd64.tar.gz"
      sha256 "68c26b9dd755f9ac2ad6da8361915acf5a4999a8c5981192375e8a02861e1f05"
      define_method(:install) do
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.4/genie_linux_arm64.tar.gz"
      sha256 "4e4b759d3d10594a501a2ed0f53475f035ef3a3ab7718fadbd9a82a36fb51355"
      define_method(:install) do
        bin.install "genie"
      end
    end
  end

  test do
    assert_match "genie", shell_output("#{bin}/genie --version")
  end
end
