# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genie < Formula
  desc "Translate plain English into shell commands"
  homepage "https://github.com/saadjs/genie-cli"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.3/genie_darwin_amd64.tar.gz"
      sha256 "24d231fac101e3cb743b2e6d3f89bc52c1e9ac10ed03865523002c1c0be3d411"

      define_method(:install) do
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.3/genie_darwin_arm64.tar.gz"
      sha256 "f1a10b38163efa989892433c1b8e58d1cc8f04ed335a42fa81a7556e8d509efa"

      define_method(:install) do
        bin.install "genie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.3/genie_linux_amd64.tar.gz"
      sha256 "6bbbf8c3a242ae955c3f2e905f627ba518bee7fd0f75c2025004ac8131313b98"
      define_method(:install) do
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.3/genie_linux_arm64.tar.gz"
      sha256 "c67615ae3ddb63e4826839d731ef0970d0be529bdb1fda3aca2be6a51c8927ac"
      define_method(:install) do
        bin.install "genie"
      end
    end
  end

  test do
    assert_match "genie", shell_output("#{bin}/genie --version")
  end
end
