# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GenieCli < Formula
  desc "Translate plain English into shell commands"
  homepage "https://github.com/saadjs/genie-cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.1/genie_darwin_amd64.tar.gz"
      sha256 "b8159f8b6e809cf4f7a185b8e5baee33c2eb2022387de45b6e4fa12ecbad79e8"

      define_method(:install) do
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.1/genie_darwin_arm64.tar.gz"
      sha256 "7ce803fd7a57123e60b546b7bccc1ee348060ab8b54c61413ecd7703e94c6c1d"

      define_method(:install) do
        bin.install "genie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.1/genie_linux_amd64.tar.gz"
      sha256 "472c889d13073aaef1cdf33a95e2ac43ae4b8f6bfd9a0382e949aebb085b2bdb"
      define_method(:install) do
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saadjs/genie-cli/releases/download/v0.0.1/genie_linux_arm64.tar.gz"
      sha256 "4128a34ccb3714f93563c6ecfab26d14e734380aed3c9fdcfbfeea812f062fb3"
      define_method(:install) do
        bin.install "genie"
      end
    end
  end

  test do
    assert_match "genie", shell_output("#{bin}/genie --version")
  end
end
